# Generated by Django 4.2.6 on 2023-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("idcourse", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("hour", models.IntegerField()),
                ("credits", models.IntegerField()),
                ("state", models.BooleanField()),
            ],
        ),
    ]
